parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Infrastructure\Application\Service\Application:
        arguments:
            $useCases: !tagged_iterator app.use_case

    _instanceof:
        App\Poker\Application\Service\UseCaseInterface:
            tags:
                - { name: 'app.use_case' }
